#!/bin/sh
set -e

USER=_sd-keepaneye

if ! getent passwd USER >/dev/null; then
    adduser --quiet --system --no-create-home --force-badname \
            --home /var/lib/sd-keepaneye $USER
fi

if ! groups $USER | cut -d: -f2 | grep -qw systemd-journal; then
    adduser $USER systemd-journal
fi

#DEBHELPER#
